// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "antivirus",
  "name": "Antivirus",
  "description": "Antivirus plugin for scanning uploaded files.",
  "homepage_url": "https://github.com/mattermost/mattermost-plugin-antivirus",
  "support_url": "https://github.com/mattermost/mattermost-plugin-antivirus/issues",
  "release_notes_url": "https://github.com/mattermost/mattermost-plugin-antivirus/releases/tag/v1.0.0",
  "version": "1.0.0",
  "min_server_version": "5.37.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "darwin-arm64": "server/dist/plugin-darwin-arm64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "linux-arm64": "server/dist/plugin-linux-arm64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "Antivirus plugin which uses ClamAV to scan files uploaded to Mattermost. See [documentation here](https://github.com/mattermost/mattermost-plugin-antivirus).",
    "footer": "",
    "settings": [
      {
        "key": "ConnectionType",
        "display_name": "Connection Type (Unix/Tcp):",
        "type": "dropdown",
        "help_text": "Connection Type.",
        "placeholder": "",
        "default": "tcp",
        "options": [
          {
            "display_name": "Tcp",
            "value": "tcp"
          },
          {
            "display_name": "Unix",
            "value": "unix"
          }
        ],
        "hosting": "",
        "secret": false
      },
      {
        "key": "ClamavHostPort",
        "display_name": "ClamAV - Host and Port:",
        "type": "text",
        "help_text": "The hostname and port to connect to clamd. (required ConnectionType : Tcp)",
        "placeholder": "localhost:3310",
        "default": "localhost:3310",
        "hosting": "",
        "secret": false
      },
      {
        "key": "ClamavSocketPath",
        "display_name": "Socket Path:",
        "type": "text",
        "help_text": "Path to socket. (required if connectionType : Unix)",
        "placeholder": "/tmp/clamd.socket",
        "default": "/tmp/clamd.socket",
        "hosting": "",
        "secret": false
      },
      {
        "key": "ScanTimeoutSeconds",
        "display_name": "Scan Timeout (seconds):",
        "type": "number",
        "help_text": "How long the virus scan can take before giving up.",
        "placeholder": "10",
        "default": 10,
        "hosting": "",
        "secret": false
      },
      {
        "key": "ToastMessageScanning",
        "display_name": "Scanning Toast Message:",
        "type": "text",
        "help_text": "Message shown to the user while a file is being scanned.",
        "placeholder": "",
        "default": "Scanning file...",
        "hosting": "",
        "secret": false
      },
      {
        "key": "ToastMessageSuccess",
        "display_name": "Success Toast Message:",
        "type": "text",
        "help_text": "Message shown to the user when a file scan completes with no threats found.",
        "placeholder": "",
        "default": "File scanned, no threats found",
        "hosting": "",
        "secret": false
      }
    ],
    "sections": null
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
